workshop-crm/config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :clients do
    resources :computers
  end

  resources :employees

  resources :tasks

  resources :orders do
    resources :order_details
  end

  root 'main#index'

end

workshop-crm/app/models/client.rb
# Customer entity
class Client < ActiveRecord::Base
  has_many :orders, inverse_of: :client
  has_many :computers, inverse_of: :client
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :phone, presence: true, length: { minimum: 5 }
  validates :email, presence: true

  def to_s
    firstname + ' ' + lastname + ' ' + phone + ' ' + email
  end
end

workshop-crm/app/models/computer.rb
# Client's computer
class Computer < ActiveRecord::Base
  belongs_to :client, inverse_of: :computers
  has_many :order_details

  def to_s
    serial
  end
end

workshop-crm/app/models/discount.rb
# Order discount
class Discount < ActiveRecord::Base
  DISCOUNT_TYPES = {
    percent: 'percent',
    value: 'value'
  }

  has_many :orders

  def price_with_discount(price)
    grand_total = price

    case discount_type
    when DISCOUNT_TYPES[:percent]
      grand_total *= 1.0 - value / 100.0
    when DISCOUNT_TYPES[:value]
      grand_total -= value
    end

    grand_total
  end

  def discount_type=(type)
    if DISCOUNT_TYPES.value?(type)
      super(type)
    else
      fail Exception, 'Invalid discount type'
    end
  end

  def value=(new_value)
    if (discount_type == DISCOUNT_TYPES[:percent] &&
        new_value.between?(0, 100)) ||
       (discount_type == DISCOUNT_TYPES[:value] && new_value > 0)
      super(new_value)
    else
      fail Exception, 'Invalid discount value'
    end
  end
end

workshop-crm/app/models/employee.rb
# Company's employee
class Employee < ActiveRecord::Base
  has_many :order_details
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :phone, presence: true, length: { minimum: 5 }
  validates :email, presence: true

  def to_s
    firstname + ' ' + lastname + ' ' + phone + ' ' + email
  end
end

workshop-crm/app/models/order.rb
# Client's order
class Order < ActiveRecord::Base
  belongs_to :client
  has_one :order_detail, inverse_of: :order
  accepts_nested_attributes_for :order_detail
  validates_associated :order_detail

  def total_price
    total_price = 0.0
    order_detail.tasks.each { |task| total_price += task.price.to_f }
    total_price
  end

  def grand_total_price
    discount = order_detail.discount
    if discount.presence
      discount.price_with_discount(total_price)
    else
      total_price
    end
  end

  def tasks_total_duration
    total_hours = 0.0
    order_detail.tasks.each { |task| total_hours += task.duration }
    total_hours
  end

  def tasks_total_duration_workdays
    (tasks_total_duration / 8).round
  end

  def estimated_due_date
    return_date = order_detail.created_at

    tasks_total_duration_workdays.times do
      return_date += 1.days
      return_date = DateHelper.add_if_weekend(return_date)
    end

    return_date
  end

  def task_list_string
    order_detail.tasks.each(&:to_s).join(', ')
  end

  def instance_hash
    {
      id: id.to_s,
      price: grand_total_price.to_s,
      computer: order_detail.computer.to_s,
      employee: order_detail.employee.to_s,
      tasks: task_list_string
    }.merge(order_detail.to_s)
  end

  def to_s
    str = ''
    instance_hash.each do |param, value|
      str += "#{param}: #{value}\n"
    end
    str
  end
end

workshop-crm/app/models/order_detail.rb
# Client's order details
class OrderDetail < ActiveRecord::Base
  STATUS_NEW = 0
  STATUS_INPROGRESS = 1
  STATUS_FINISHED = 2
  STATUS_COMPLETED = 3

  belongs_to :order, inverse_of: :order_detail
  has_many :tasks_to_order_details
  has_many :tasks, through: :tasks_to_order_details
  belongs_to :discount
  attr_readonly :status
  belongs_to :employee
  belongs_to :computer
  validates_presence_of :order
  validates_presence_of :employee
  validates_presence_of :computer

  def status=(new_status)
    current = @status
    @status = new_status
    @status = current if @status != STATUS_NEW &&
                         @status != STATUS_INPROGRESS &&
                         @status != STATUS_FINISHED &&
                         @status != STATUS_COMPLETED
  end

  def to_s
    {
      status: status.to_s,
      discount: discount.to_s,
      created_at: created_at.to_s
    }
  end
end

workshop-crm/app/models/task.rb
# Task described with its duration, price, title
class Task < ActiveRecord::Base
  has_many :order_details, through: :tasks_to_order_details
  validates :title, presence: true
  validates :price, presence: true
  validates :duration, presence: true

  def to_s
    title
  end
end

workshop-crm/app/models/tasks_to_order_detail.rb
# Many-to-many tasks: to order details
class TasksToOrderDetail < ActiveRecord::Base
  belongs_to :order_detail
  belongs_to :task
end

workshop-crm/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client
    else
      render 'new'
    end
  end

  def show
    @client = Client.find(params[:id])
  end

  private
    def client_params
      params.require(:client).permit(:firstname, :lastname, :phone, :email)
    end
end

workshop-crm/app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  def create
    @client = Client.find(params[:client_id])
    @computer = @client.computers.create(computer_params)
    redirect_to client_path(@client)
  end

  private
    def computer_params
      params.require(:computer).permit(:serial, :specs)
    end
end

workshop-crm/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  private
    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :phone, :email)
    end
end

workshop-crm/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

workshop-crm/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @order.build_order_detail
  end

  def create
    @order = Order.new(order_params)
    @order.build_order_detail

    logger.debug @order.order_detail.inspect

    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private
    def order_params
      params.require(:order).permit(order_detail_attributes: [:id, :employee, :computer, :tasks, :discount])
    end
end

workshop-crm/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  private
  def task_params
    params.require(:task).permit(:title, :price, :duration)
  end
end

workshop-crm/app/helpers/application_helper.rb
# App Helper
module ApplicationHelper
end

workshop-crm/app/helpers/clients_helper.rb
module ClientsHelper
end

workshop-crm/app/helpers/computers_helper.rb
module ComputersHelper
end

workshop-crm/app/helpers/date_helper.rb
# Date helper methods
module DateHelper
  def self.add_if_weekend(date)
    date += date.saturday? ? 3.days : 0.days
    date.sunday? ? date + 2.days : date
  end
end

workshop-crm/app/helpers/employees_helper.rb
module EmployeesHelper
end

workshop-crm/app/helpers/main_helper.rb
module MainHelper
end

workshop-crm/app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

workshop-crm/app/helpers/orders_helper.rb
module OrdersHelper
end

workshop-crm/app/helpers/tasks_helper.rb
module TasksHelper
end

workshop-crm/app/views/clients/index.html.erb
<%= link_to 'Add new', new_client_path %>

<h3>Listing clients</h3>
<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Phone</th>
    <th>Email</th>
  </tr>

  <% @clients.each do |client| %>
      <tr>
        <td><%= client.firstname %></td>
        <td><%= client.lastname %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client_path(client) %></td>
      </tr>
  <% end %>
</table>

workshop-crm/app/views/clients/new.html.erb
<%= form_for :client, url: clients_path do |f| %>

    <% if @client.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@client.errors.count, "error") %> prohibited
            this client from being saved:
          </h3>
          <ul>
            <% @client.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname %>
    </p>

    <p>
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname %>
    </p>

    <p>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', clients_path %>

workshop-crm/app/views/clients/show.html.erb
<p>
  First name: <strong><%= @client.firstname %></strong>
</p>
<p>
  Last name: <strong><%= @client.lastname %></strong>
</p>
<p>
  Phone: <strong><%= @client.phone %></strong>
</p>
<p>
  Email: <strong><%= @client.email %></strong>
</p>

<h2>Computers</h2>
<% @client.computers.each do |computer| %>
    <p>
      <strong>Serial:</strong>
      <%= computer.serial %>
    </p>

    <p>
      <strong>Specs:</strong>
      <%= computer.specs %>
    </p>
<% end %>

<h2>Add a computer:</h2>
<%= form_for([@client, @client.computers.build]) do |f| %>
    <p>
      <%= f.label :serial %><br>
      <%= f.text_field :serial %>
    </p>
    <p>
      <%= f.label :specs %><br>
      <%= f.text_field :specs %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', clients_path %>

workshop-crm/app/views/employees/index.html.erb
<%= link_to 'Add new', new_employee_path %>

<h3>Listing employees</h3>
<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Phone</th>
    <th>Email</th>
  </tr>

  <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstname %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
        <td><%= link_to 'Show', employee_path(employee) %></td>
      </tr>
  <% end %>
</table>

workshop-crm/app/views/employees/new.html.erb
<%= form_for :employee, url: employees_path do |f| %>

    <% if @employee.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@employee.errors.count, "error") %> prohibited
            this employee from being saved:
          </h3>
          <ul>
            <% @employee.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname %>
    </p>

    <p>
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname %>
    </p>

    <p>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', employees_path %>

workshop-crm/app/views/employees/show.html.erb
<p>
  First name: <strong><%= @employee.firstname %></strong>
</p>
<p>
  Last name: <strong><%= @employee.lastname %></strong>
</p>
<p>
  Phone: <strong><%= @employee.phone %></strong>
</p>
<p>
  Email: <strong><%= @employee.email %></strong>
</p>

<%= link_to 'Back', employees_path %>

workshop-crm/app/views/orders/new.html.erb
<%= form_for @order, url: orders_path do |f| %>

    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@order.errors.count, "error") %> prohibited
            this order from being saved:
          </h3>
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.fields_for @order.order_detail do |od| %>
        <p>
          <%= od.label :computer %><br/>
          <%= od.select(:computer, Computer.all.collect {|p| [p.to_s, p.id]}) %>
        </p>
        <p>
          <%= od.label :tasks %><br/>
          <%= od.select(:tasks, Task.all.collect {|p| [ p.title, p.id ] }, {}, { :multiple => true }) %>
        </p>
        <p>
          <%= od.label :employee %><br/>
          <%= od.select(:employee, Employee.all.collect {|p| [ p.to_s, p.id ] }) %>
        </p>
        <p>
          <%= od.label :discount %><br/>
          <%= od.select(:discount, Discount.all.collect {|p| [ p.to_s, p.id ] }) %>
        </p>
    <% end %>

    <p>
      <%= f.submit %>
    </p>
<% end %>

workshop-crm/app/views/orders/show.html.erb
<p>
  First name: <strong><%= @order.order_detail.inspect %></strong>
</p>

<%= link_to 'Back', employees_path %>

workshop-crm/app/views/tasks/index.html.erb
<%= link_to 'Add new', new_task_path %>

<h3>Listing tasks</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Duration</th>
    <th>Price</th>
  </tr>

  <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.duration %></td>
        <td><%= task.price %></td>
        <td><%= link_to 'Show', task_path(task) %></td>
      </tr>
  <% end %>
</table>

workshop-crm/app/views/tasks/new.html.erb
<%= form_for :task, url: tasks_path do |f| %>

    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@task.errors.count, "error") %> prohibited
            this task from being saved:
          </h3>
          <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :duration %><br>
      <%= f.text_field :duration %>
    </p>

    <p>
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', tasks_path %>

workshop-crm/app/views/tasks/show.html.erb
<p>
  Title: <strong><%= @task.title %></strong>
</p>
<p>
  Duration: <strong><%= @task.duration %></strong>
</p>
<p>
  Price: <strong><%= @task.price %></strong>
</p>

<%= link_to 'Back', tasks_path %>